version: "3"
services:
  selenium-hub:
    image: selenium/hub:${SELENIUM_VERSION}
    ports:
      - "4444:4444"
    healthcheck:
      test: ["CMD", "/opt/bin/check-grid.sh", "--host", "0.0.0.0", "--port", "4444"]
      interval: 15s
      timeout: 15s
      retries: 3
      start_period: 30s

  chrome:
    image: selenium/node-chrome:${SELENIUM_VERSION}
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PORT=4444
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_GRID_URL=http://localhost:4444
    ports:
      - "5900"

  firefox:
    image: selenium/node-firefox:${SELENIUM_VERSION}
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PORT=4444
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - START_XVFB=false
    ports:
      - "5556:5555"
    healthcheck:
      test: ["CMD", "/opt/bin/check-grid.sh", "--host", "0.0.0.0", "--port", "5555"]
      interval: 15s
      timeout: 15s
      retries: 3
      start_period: 30s 

  node:
    container_name: e2e-tests-container
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./report:/usr/app/report
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PORT=4444
      - CIRCLECI=${CIRCLECI}
      - CIRCLE_BRANCH=${CIRCLE_BRANCH}
      - CIRCLE_SHA1=${CIRCLE_SHA1}
      - CIRCLE_BUILD_NUM=${CIRCLE_BUILD_NUM}
      - CIRCLE_BUILD_URL=${CIRCLE_BUILD_URL}
      - GITHUB_ACTIONS=${GITHUB_ACTIONS}
      - GITHUB_REF=${GITHUB_REF}
      - GITHUB_SHA=${GITHUB_SHA}
      - GITHUB_RUN_NUMBER=${GITHUB_RUN_NUMBER}
      - TRAVIS=${TRAVIS}
      - TRAVIS_BRANCH=${TRAVIS_BRANCH}
      - TRAVIS_COMMIT=${TRAVIS_COMMIT}
      - TRAVIS_BUILD_NUMBER=${TRAVIS_BUILD_NUMBER}
      - TRAVIS_BUILD_WEB_URL=${TRAVIS_BUILD_WEB_URL}
    depends_on:
      - chrome
      - firefox